### ISSUE TITLE
Add support for OL and OB from Mir(?)BSD

### ISSUE THREAD

**Issue by Natureshadow** [Natureshadow/mmllib#4]
cf. https://www.mirbsd.org/htman/i386/man4/spkr.htm

**Comment by mirabilos** [comment]
… fine, then you don’t want a review…

**Comment by Natureshadow** [comment]
>… fine, then you don’t want a review…

Yeah, I obviously held the commit back for over a week just for fun.

Go somewhere else for arguments, please.

**Comment by mirabilos** [comment]
Dominik George dixit:

>>… fine, then you don’t want a review…
>
>Yeah, I obviously held the commit back for over a week just for fun.

You knew I was ill, *and* I told you before FOSDEM I would not have
any time before this week (in which I was ill).

>Go somewhere else for arguments, please.

Pff…

//mirabilos
-- 
<igli> exceptions: a truly awful implementation of quite a nice idea.
<igli> just about the worst way you could do something like that, afaic.
<igli> it's like anti-design.  <mirabilos> that too… may I quote you on that?
<igli> sure, tho i doubt anyone will listen ;)

**Comment by Natureshadow** [comment]
>>Yeah, I obviously held the commit back for over a week just for fun.
>
>You knew I was ill, *and* I told you before FOSDEM I would not have
>any time before this week (in which I was ill).
>
>>Go somewhere else for arguments, please.
>
>Pff…

The issue tracker is not for arguing for argument's sake.

Looking closely, you have full access to the repository, so I see nothing that should prevent any fixes from your side even after merging.

Please fix anything you have to fix - this discussion makes no sense.
