### ISSUE TITLE
Creative Commons content is no longer welcome on GitHub

### ISSUE THREAD

**Issue by mirabilos** [Natureshadow/mmllib#6]
As per http://www.mirbsd.org/permalinks/wlog-10_e20170301-tg.htm the file https://github.com/Natureshadow/mmllib/blob/master/examples/pachelbel_canon.mml must likely be removed.

**Comment by Natureshadow** [comment]
I cannot find anything leading to that in the new TOS. Please clarify.

**Comment by mirabilos** [comment]
Attribution is required to be waived by §D.7 – and Steven David Tung most certainly did not waive it.

**Comment by Natureshadow** [comment]
This does not need to be tracked in every single issue tracker.
